---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dev-app-secrets
spec:
  encryptedData:
    API_KEY: AgB6heLfm9XdCLvmLiETP08JWMjlLalQ8kQ5sfhl9jXsr+255o7ETzS1Aa6q0eJzrXfSVkRsd6V4VMNQAWXYXgcARJlFr80olDLQSMDeumAH/qieGPkwV+RCvAw93D6UpbI0TwRFs/gROT/iUyryzlF/j2AB341fMTvQcP3RBBWtpRM9BQ2OWqca0d2GEPrTksQg8P8XvfmJAhXAJl+TC0cRsED88NgVOpaNQXkuiOymCAD2gOdLxjmBXTVzaAD8/5BtSsKoSTlSRmcX8ied5kA0KXH7G439KP10A0WsDt9pJIm5RWtc5qt40vYF0PdAuLV9bcV2WRABzvzkdhtr1sbiFrol70PQ0PbgzEWYhrreba7Lnw3phyPhIgSsns0dCx0jONfmiFzWs9RngfYq1lUv2XdoREixkuUJxIkHt3UzqFXSvAAy0AaXW7GHyoAXCEI23Q3MJIxhPVonGlRyR6PkzguS++RED4P7CuPxbpk8JKl5zupbwBpDJ+jpDomjwSe3XYIe4t81GVGMxeno+RgISVSIYOoabaE7JL4wC9/7dVgRp/fiHZt8yWf2krn6LFV0hZXeX/95KwNI/ya2zf2IwDn3Njy8OeGXqueuDpQEiXFgxsmX4iaOqRCujNbhIytARM53BYU4WeRa3vPFYi4Fc9+6+H0quH/pC9kPW67jvAhNYo9ZiR20gzxYAnqopZ522nbpEHf+Jvbcz3Qkd9ozS6C5JA==
    DB_PASS: AgB3+g0j6gYvf3Wvkqe/RsZpNpXEb6alAI/rnmRvznJuA9hjV1MdkzdJSNytCikQecOexhIoYgNQDRcWczH9GyT2xNZkWivDwi1uXBql1UwsbXdy44vv4aq4l2ceymjtNgJKTyFZr+V2AXYd7LOVUY4evCaoqIJnp+165E+Tgiju3PKkTOfrnJTPCISknuiJukYPY1sXehlyspe5hfKuE1CyLmsUc5lEPwmzb6qjpnI/TLt+vl/CUqI2ZGqo0AaMMebeySyqxo/9AO8+1VAv7ttX4IeD6Wnb5BY9NlMbpGCFPtJuoIz5NP1wZVdzcvjl/YPcROuOPSZn+tqYR6Zf3WdBPyW4NuPLMZ8b34aiJ7TOfB5CVo3K/zrzT5GKHdbIvGBulrKFr8maChqiHFyIjx9NzsTwfk/eujDdTUqmwneCzCfdOvw1In73WNuupTYklezgtcEjbUeheWCfnTnm40N/JuffHbiX2T72pTBt3K5wAjSEmjBhhZ485VQtkzTaovzqKj7E8xZTzMTQlSpKIxJh1tvRDckbqiAbd1TWDfHwFGnMjEMf7Spc6ve4EgzDKJqroGS3BNHrNGJV8GNfomAjJw+az3M0gff6S6wrhSJy+nrefdHJnLdBKq+OYKzpKwNkb4jx+T55ucrKOSr6n44eZd4c+EwoOkJVTO8qigFf2hIolOODuGxKrms2EfSWecNDd6VBsGIwxe2yOchLsFD0z8jq
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dev-app-secrets
