---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: dev-app-secrets
  namespace: dev
spec:
  encryptedData:
    API_KEY: AgCwTaaTLRlk1j0H7g9C7SxCxroyMLgFPk5hygoi2uCmXHb4e3j0aSg0yH2frnxkrHUdB1l4X/TZNE2aFi91GGl78nzfUBcgNudbGZnJhYTbfT/Nrgr3h0tUIV3g8HHSCmwYYaY/xCL9+6+LRgsp66Njc2umDLka3kmPIuJR2fR3n8QgMhEusrtUdXQrAg/SExWhNbdCb9rsOoHal2ikWVc5ablGpGka8k3TH4AmDxxyQTXcGa4Kc02DcXJ02TkmFUL8rMaJyDLHSPfqdWs6txyHVU1o6/4pSaGccWJQ8O21gDp7//2yHXF2FM9N/kX7wCY6a9JAnOqQi7B8V1to3wS3uapm//cjR9zl36+13++MGKoUSMArT02KjE+vhQUchyl5jt1dLs6Psx2lMspM3407wjCjNJF1r6vHpGem7aoHah/eEovKAXFMKE2Zik1/uSyxwUfluprwYmPRiUbvw1GdriGK9fo+mL6Zk5ECbmeLvkbjPZRFR1yf9JZc4m1E77wPRW24YTM7W6MCEQuh9PMcSGT602Zo/TDUN8pkuxRxA+f2+XyfgXKAS2Jn4jJ2qvFgY2A7uCkimw4/fqUZXrojtSzNPro7wq583X/y4CNcx7Pmv5w+NnZRAzSjpvPxpy51oetwIRpHTPPvs4yKtktI1MkN9iwJh9r93v5P2DSN33UcaHd+wdwb6cCeLfSllIz1IsQL1IXIOoOuraQ/Xz+4OaXdxg==
    DB_PASS: AgBWPqrywiqUL+YAhqCLaJEfXYFyJqDin+UbfTnadGijPR7ilS8gsqxUbI73U+E527rx+ig3WA2tk8EeVpkn3XR/rfqPL9r9pAE7DLUm0j+cpxgIQSeNaxNv1ZgZ9qbH9/vQLkYDj+4VmAHKX4ffpuSGxjhR2X3DYoztre5Mp7S7UP6H3kp3KJfkiQbiqZEcEvSm+NPmXIRVR2p/RH99ySvfOJOXYtiH14jt1Thqb8xq77kiY4bfAjYbuK3geksjgJTq0bIVJEdS8fvynkgeAbDMADK5I76m3Axj1mTDAhby74sWKmetOqm16EeJDFqoN8NBtmfqK0lOMoVVkHlkP2jW3Bfttetx56WW48ZPcnTK92cCzd5VugGI5EVb9BEKjktomEPzGMmLzNF1mLvQa6ButI4EWpGUW8LZ5N5cw79/eSvUx2RWHTheiqZmth+dDlaDZjhDgzsM535vzVzw95oyre6EYNlCFISsAS+SSzEwylr61+3yONa/wbXNMkd9RPosYaY766UZwq4YBexpgtntW/OfO+CqVwcQoU86OiYHvlpAXScfHEQ8Airid/iPDEWJMBT0wTfrGOTqBjcJ8l+mU+2AgZdb1+ZGKvbfMUNQV/JCwNHjFe4dRf9H+vVB5mAOC/e11HoebP2dehOfpIZptCFNzxBCV3Qs+ohEGJJBHRkCZ6Nbf6XYoD1LqFevIL9dlFXVLf2yZ9vmDxBPvS51Fuvv
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: dev-app-secrets
      namespace: dev
