apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}helm-world-service
spec:
  selector:
    app: {{ .Values.namePrefix }}helm-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
