apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-check
spec:
  metrics:
  - name: prometheus-success-rate
    interval: 10s
    # Evaluamos directamente el valor numérico devuelto por la consulta PromQL
    successCondition: result >= 0.95
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus-service.monitoring.svc.cluster.local:9090
        query: scalar(avg(up{job="prometheus"} or vector(1)))
