apiVersion: argoproj.io/v1alpha1
kind: Rollout 
metadata:
  name: hello-world-app
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        # 🚀 CAMBIAMOS ESTA IMAGEN POR UNA MODERNA Y ESTABLE:
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: PROMPT_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-messages
              key: MESSAGE
  strategy:
    canary:
      steps:
        # Paso 1: Enviar solo el 25% del tráfico a la nueva versión
        - setWeight: 25
        # Paso 2: Pausa indefinida para que el administrador apruebe la versión
        - pause: {}
        # Paso 3: Incrementar al 50%
        - setWeight: 50
        # Paso 4: Pausa de 20 segundos para prueba automatizada
        - pause: { duration: 20s }
        # Paso 5: Incrementar al 75%
        - setWeight: 75
        # Paso 6: Pausa de 10 segundos antes de ir al 100%
        - pause: { duration: 10s }
