apiVersion: argoproj.io/v1alpha1
kind: Rollout 
metadata:
  name: hello-world-app
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        # 🚀 CAMBIAMOS ESTA IMAGEN POR UNA MODERNA Y ESTABLE:
        #image: nginx:alpine
        image: nginxdemos/hello:latest 
        #command: ["sh", "-c", "sleep 3600"] # No levanta puerto HTTP 80
        ports:
        - containerPort: 80
        #env:
        #- name: APP_MESSAGE
        #  valueFrom:
        #    configMapKeyRef:
        #      name: app-messages
        #      key: MESSAGE
  strategy:
  blueGreen:
        # Servicio que recibe el tráfico de producción
        activeService: dev-hello-world-service
        # Servicio para probar la versión Green antes de promoverla
        previewService: dev-hello-world-preview-service
        # Pausa para aprobación manual (o podés usar autoPromotionEnabled: false)
        autoPromotionEnabled: false
        # Tiempo que se conserva el entorno viejo en standby por si hay rollback
        scaleDownDelaySeconds: 30
