---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-app-secrets
  namespace: dev
spec:
  encryptedData:
    API_KEY: AgBUFnFfAKkBt2h3nulLVGiRrOdn4D9eqOxU2IEtLUW7uFN0iFkfm/H/rbnTVILHorHdVMniW7RRuLAhYqKOsWNeggDpYJO38fpF1t2xUpPR1hRmvrIsdK9IkbEuc5YUnSGMEaws4SLcnPfiHpnjiQss+/EqV1ia83fqsuaNH7QONePzhg7SLwRaUxd6Ap2VfHJykIAa6ong6y5Fxsg/z+W8gc/etPBD0kfq3wuYXYeJrehVBb+l3JTwLiyZvhimUzLk/uL24+TCwXbwepH20hDY6ps4jzWgIKtz601Mjrr3s+5m58unF4P9jYa++gSW2sL0Lkb9NV91dtsIuTQSDw7rm9kkQiTKmCcZi39ZeNVk5Peod0BE8Wjb6t7FvFk8z5YBzkN51lLQxjZSgReV2oa8xS249mNC05h9B/qj6G/3NiLya8uXwqTKH8qCZN5Yt4iQTfgvVlTRQfuiIhoiwK9g20g3Gj5YBeBWGsSF1bQ5v1c4g2zMDmZ0EtuyWSwA/vKMBdB20dcd/48AQDl55C2DxoB/ypCoFc5dIiXcE/aZTkRCbFShXudN7A7NipVgMWUPyyBhLqViPKhgwBcj1xi3O4+pnAoMaIVmRnpVv3NXyp7tbRw7lX+SunM9woLGi9LVyYTGglJGNabI+ZD4pezuzx3IzY+YishvHJje19kPu0ka4jHMAwXZrXudaYLY+YPw047LEXiTRUJvI2Vq2CKsPCV7YA==
    DB_PASS: AgDBkjhfwaa8qyeTWptyeNsMsiUeePbp3Py1oQ0iicoWRR6t+9+4DGRnr1ivS3g66sx7Q/dmuhCPzfzTPt/3+1kshHTutjlQGHmHImnang/MIWcCnfkjV/5ikPlr0AqZpAihHzVUx9exBTzFYha88zEqAoSzN7eO/fSkKaVambfHlnKxRBP6IFDwDzpVsXA2qjXtZ15GAAYF6EPHScy3sc/h6VqJtQ3CUPARqTNRmlPrzk5p3i/MEeJa3oXuHSKMMG6sqYErdZM0GspDJEXmYxytDCshB0dcP3JOusCkC6cSFxeW+df2dx1Ab4CuvbyJKX9H8HKiBCZdLPFW0VOwAXn57QkekvzalFPxk6EualvFa23onCQ5xuIrT4PHPZVejKVBTFtCFnpAoBhVNQwPxggrkN5pijH+eWlcQiwFGJOp2TrffSpR9poegRBfk4cyknn7PJTym8GPzFXFMh82Xhu7dIWNw/kPpEVYS00oCDd+6UVK+cL3HTggYedcrZjYecAC9n/C+LuThiaiwpfaEoaYYIRIzM0uQXGvMbNR9VGQePVBjQEere2mWSEwYAXFuO4iyogG9miNee15JR9dWpwy0A72va2WtIlgDrk7TYKGu6e6CfRZfjXQJ182/NBUIifKD+8Xt7RCQGzikmbRCz0+rUktPPD5Dr3GP1izyPe/L16y/6cyGiW4KQZH7FTa2lqRKMTeaxzsCB+Ba2opF2v8yjx4
  template:
    metadata:
      creationTimestamp: null
      name: dev-app-secrets
      namespace: dev
