---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-dev-app-secrets
  namespace: dev
spec:
  encryptedData:
    API_KEY: AgCCwP4GivXVOEnIRZgFF9PAx5/W4PzpVqotrJiUpKIADp1oElECoGsGAGARqwvYuMlaKl8dUsuEQdarF85IAg1YGVZdnW3aSDvTdYBs4G5wp1hnrdNCLtLk6w6b/0y5NGKKpQ+xO7MDuTFH7cgxhmcgrkQZfih7V4dEYXO46OZejiLDKByIPM5jQkKbtX7J54lbDUBy7G3/IuOwyoIoGGu5opde1Nach5ihMR9YbVxdGhnhRNAZ4xqCBxEB6v6q8rJX/VI44J6LRnCiBiUBx4osX7d00jkTcb0PQmJQ5ItsFIEEklFaB2JdbcNJboaCs7pS8QXqYPGkUlINJNnhM2SkeOezGbW3EE+jnLl1Y1BnEXr7pLb4/yV4+Xx0kvffsiVg9XyVUlngnuxMwlhGPxgZR6iXIXdi6C1FbPek9RlPCm6yRRFe8f3Ivprs3bkphYnSN8oLWHsART9TGed7fYY4O3PhJt7QxBrDMn7HSa1ElrtY0XVdnmmx7ZSyFfiWdQVHQuxlIfSTG0s5ZHx8WY+Yf1Y5vXOZjLQKnOVJQB78evpo91QYrgh77PC1JSVSr6DNB2eQZBLoNgvkgaj2AQqzRqRjj0s4xVRqrtvDRx8fto3HOgr79zs03DuZ2vWx9u4BG1R7aDtx8kaN6ziSHJNtrhFQ32NODWp5/gvPL/5/GGcEANjp3cGMsc1hNv2k/ahbLua6IUIE8YT+fKVf47+XuLIIZA==
    DB_PASS: AgC+wfYTu6YfsUxGEewzwJbJHYGMxJCa7fdGq1aInGTtYl4Iko+KNYqFCTVfGne70idPXenkKOjU5U/TdRT37D3mBLHu9vccp9lwmws1jrQjttPhU3bimCemyf1HcZBppyX6YBv84HUlRSaavuAWQiRr61b1osifoWTU5Wl5jyiqGu5/BIMOOUw1kzFJAhjnkA/j8zCxryxckkIk77QghcTvsdvNv7Np7Tnu4sNUNmCrId4oLiMXbWCEXTQgPaftDmm/INKHyaqPCjzQdNJH8UQi8YDG8G9dSXIsa+/5KepBWd5IZbUQXisM87RgyInPaE6RMhbuOh39ueIZiX35wDMf2SxxE+PFPXNiKXGBeD7a0cFBDipUXdGe2W9DC4rQmlXTKMRZnff0vkNZvqi38uLNxC76lMrcFntZF68mmVWxhY9qtxMv0Wy8aGDz+iRAD5TkC8hnmIoIIXcJIv9eEvuO6UWLA9mTKqaIkrEt9Leh7sgf3c7LzLxfB44tq6Gt+PZepzhZ1dB7v5THdN2Ma0Z0Y7IPrFKOlhmLWJVf8tzpcFNr+SgrCOIHuwQrp/EGroV4sf13dxCDr9KvQZbwqg0AcO2cltp/tAdR2dNtZ+kHtsxZHmh8Z074npNLIzgnJ28aiKxyZoP1KMeaznnzusD/tT2LqUq4VKHCEnxoR+oK1XSjEPfvSLrC9zN3MCN0LYqAxsjTNApbYc/MCmr4OdmjxG4/
  template:
    metadata:
      creationTimestamp: null
      name: dev-dev-app-secrets
      namespace: dev
