---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: dev-app-secrets
spec:
  encryptedData:
    API_KEY: AgDYUeSV14BBnXSupgNfkdPS/YmbFt5uwdeC+079p3tnwUmyXGW8NAnQiLiOVR4E0r8s+ore4h9hHnXUoCTjjN/1s60M4nIGGoXdSvgT6z2IdH51dDLklbI0iQAF3jmmsbkCqF1KkublOGfs1rLjv1OnAOXAoPaKFFNVYfJvzkpCguIJczItcvpP23WRnMMHKbsDtZM/2NBTOrKL3RDeQ4JWopmXeGGpkHxetoapoIV6jGQMfss36sSeqpzeYVJX+eNq45uSwE3hkq9gYU6zGRssiMFIFXnOyL8g+Z9eBHe/B7KTsxDYIvLSm7mS5HsNawQiWEcz5leQgtBYdhmv6e5x63wFii72tqXOPNf+iJkIGm4AgmfcgQnDZu/g1L1zo5gdqkJ4Ku6D6iit2Zx36E9loNUAEejvUdG9BvQgYSe5XlPiqo83+YxWzkS2UirJloaBUftmWRoEM3NIsOQ/bNe9aSKA3QPjaORVhtEfl1uSHixZ8MBMh2/ILbZ++isUCfsEctmRdThxfoWWUFAfxpHPuhghqUOrI+HIwznGJtV6K1/4xTNq/rl4IRqAgczkHmW+DGrFCIGt2JSDWxgxGWmK17xI8+HkipK6vEHTFGQvh7QYyDm0XpU5hjXGFZOZSc1Zp1nPJdI3lXfpu3k/uwE0NBjPtwRV5g+foalCWr47X6xe76+D4iz9mJUcWXO6HpfmB3WkpHfZgpNUlbjNpI3UusxJJg==
    DB_PASS: AgB/ijCNPQz4514Z9sHiWkuwi+rnlpJauWkE6MRWR/E1T0gy1UB8IfVBvHNBibgOVUf3kqpVTw1XiZJ2eHDqIXNvVCvjl1TXM18UQc5z7YaNuiDlYlzTGqHzi/2dsaKGAzCBbFvlwGs4V6l9HahufY6czLAsaxMYDLoE1MbHHLGIry097Bwx57M+oa44kH9tllJEYTU3YVBciKWmm2J/bu8LnU6LXpEKdx2nNnlSR9JuKbd3tTaL5pD4IR0jQYQLx99aQ6iFYboBDX4Zuk+zaN0OXd82jisWlOxSHmEFSSA4FpBLReLFHRWBrsCPdIFh8VWhYjL+oqRbq8XC4cwCewRpLU2ra14iOyB6zza3qfvtCkdmmBq9W2cO4xRNKtaEHGgj4lJp6XZSaKOMowkAGWDRz89810OHteal3NF0tSKcMK5bpJwZ5wJnRIPqgJqT52NddEkAjOvYc6JfEYybP09q8IJULxZrDuRGkrua5qRv2MsYhytBz03tVtGuJhj7NXReOWej1ATXNrFKOmOesDfVQ9GscqEQfpDVClGEiU8kuHnDKLA4Lgf1sgda33vvsHIiPh+b24NSjBmtMzkCIYj8nOXNJeEt8AEfkJ2xhDGI0R0NCf/9wBMLy6GORKHjz8+shUaJyzuw8jtXgJY60AlQkz8xFXulwdzcvyeDsf3TE0aPTTK6sQdEYergTjuG0989eM5lYgaZfMy7K5mY+T1T2sFw
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dev-app-secrets
